### ISSUE TITLE
Ensure OpenAI token consumption to be measured with agent running duration

### ISSUE THREAD

**Issue by Rindrics** [giselles-ai/giselle#128]
## Task description

- update instrumentation of `tokenConsumed` from metric to structured log.
  - to ensure that token consumption is paired with duration of agent run

## Background

- We want to get each metrics in terms of values **per duration** of agent run

## TODO (Optional)

- [x] configure OTEL log to be sent to telemetry backend
- [x] update current instrumentation of `tokenConsumed` to be measured as structured log
- [x] embed new measurement `duration` into the structured log
