### ISSUE TITLE
Install Vercel GitHub App

### ISSUE THREAD

**Issue by shige** [giselles-ai/giselle#13]
## Task description
Please install the Vercel GitHub App from the following link:
[Install Vercel GitHub App](https://github.com/apps/vercel)

## Background
Since the source code was migrated from another repository.

## TODO (Optional)

- [x] [Install Vercel GitHub App](https://github.com/apps/vercel)
- [x] Create a pull request in this repository
- [x] Confirm that a Vercel Preview environment is automatically generated.
- [x] Confirm that a Vercel Production environment is automatically generated.

**Comment by shige** [comment]
🤝 

![Image](https://github.com/user-attachments/assets/959f495f-dfd3-410a-bb2c-0dfda42b70e4)

**Comment by shige** [comment]
> * [x]  Create a pull request in this repository
> * [x]  Confirm that a Vercel Preview environment is automatically generated.

- https://github.com/route06inc/giselle/pull/15

**Comment by shige** [comment]
> * [x]  Confirm that a Vercel Production environment is automatically generated.

🚀 

![Image](https://github.com/user-attachments/assets/13bcdd86-52f4-49e6-9825-b84f7fd70c39)

**Comment by shige** [comment]
All done ✅
