### ISSUE TITLE
Migrate from bun to npm, pnpm, or yarn as the package manager

### ISSUE THREAD

**Issue by shige** [giselles-ai/giselle#215]
## Task description
Migrate from bun to npm, pnpm, or yarn as the package manager.

## Background
- It's inconvenient that I can't check the differences on a GitHub pull request and also can't provide the context to the Copilot Extension for review.
- This task is necessary because currently, using `bun:test` with `mock.module` does not provide a way to reset the mocks. 

Transitioning to npm, pnpm, or yarn will allow for more flexibility and might resolve the limitations encountered with bun.

## TODO (Optional)
- [ ] Evaluate and choose between npm, pnpm, or yarn.
- [ ] Remove bun from the project and install the new package manager.
- [ ] Update the project's dependency management scripts to use the new package manager.

**Comment by toyamarinyon** [comment]
I was the one who adopted Bun, and I currently think we should migrate to npm, so I'll write down my thoughts.

First, the initial issue mentioned in the background is resolved by Bun v1.1.39, which enables text-based lock files.

https://x.com/bunjavascript/status/1866879040424120625

![image](https://github.com/user-attachments/assets/bbb16a9d-298e-49c5-adee-4cc5e1f9b73a)

However, Bun is not being used as widely as I had imagined. In particular, most publicly available OSS applications that developers can try out immediately use npm or pnpm.

Vercel example (pnpm): https://github.com/vercel/ai-chatbot
OpenAI example (npm): https://github.com/openai/openai-realtime-console
Supabase example (npm): https://github.com/supabase-community/database-build

If this trend doesn't change, I believe switching from Bun to npm (or pnpm) would be a better choice for developers.

**Comment by sakit0** [comment]
@toyamarinyon @shige 
How about adopting pnpm?
The following is the reason.

- With npm, I get an error during installation due to peer-deps.
  - To solve this problem, specify --force or --legacy-peer-deps
  - pnpm automatically resolves it during installation
    - Same behavior as bun now.
- pnpm allows you to specify the version of pnpm and Node
  - corepack has been removed from node, but pnpm can still be managed by itself
  - manage-package-manager-versions: https://pnpm.io/ja/npmrc#manage-package-manager-versions
  - use-node-version: https://pnpm.io/ja/npmrc#use-node-version
  
- If there is a future for mono-repo, pnpm will be more advantageous
  - [pnpm Filtering feature](https://pnpm.io/filtering) is not available in npm
  - pnpm creates one lock file, npm creates multiple.

If agreement is reached on pnpm, I will make a PR.

**Comment by toyamarinyon** [comment]
@sakit0 Thank you for summarising. I expect to use workspace (and turborepo) in the near future, so I think pnpm is fine.

**Comment by shige** [comment]
@sakit0 I also think migrating to pnpm is a good idea!

**Comment by sakit0** [comment]
@toyamarinyon @shige 
Thanks for the review.
I'll work on it.
