### ISSUE TITLE
Remove the `web-search-node` feature flag and release the feature to the public

### ISSUE THREAD

**Issue by shige** [giselles-ai/giselle#63]
## Task description
Remove the `web-search-node` feature flag and release the feature to the public.

## Background
The new Terms of Service have been published, allowing the removal of the feature flag. You can review the updated terms here: https://giselles.ai/legal/terms

## TODO
- [x] Remove the feature flag `web-search-node`.
- [x] Ensure that the feature is prepared for public release.
- [x] Deploy the changes to production after November 06, 2024.

## Additional notes (Optional)
- Make sure to coordinate with the deployment team to schedule the release post-Effective Date.

**Comment by shige** [comment]
Released in https://github.com/giselles-ai/giselle/pull/99
